services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules   
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    command: npm run start